### ISSUE TITLE
window.foxitAssetURL; returns undefined

### ISSUE THREAD

**Issue by wh33li3** [jyooru/pearson-pdf#175]
window.foxitAssetURL; returns undefined instead of the desired url.
any workaround or did they change the functions?

**Comment by jyooru** [comment]
Hi! Thanks for opening this issue. Unfortunately Pearson seems to use different software to access different books. I've had reports that window.foxitAssetURL sometimes returns a URL that requires authentication, and I haven't been able to fix those as I can't test them using the books I have.

This is the first I've heard of it being undefined. If you've made sure window.foxitAssetURL is spelt correctly, there isn't much else that can be done. All of the books I have work with this tool and I'm not sure why your book is different, so I will be closing this issue. There might be an alternative you can use.
