### ISSUE TITLE
pearson_pdf.PageDownloadError - plus.pearson.com

### ISSUE THREAD

**Issue by rlsolomon** [jyooru/pearson-pdf#38]
window.foxitAssetURL; returns https://plus.pearson.com/eplayer/pdfassets/prod1/109693/4e309576-c7ad-42f5-9663-ce760d9e20bc

running
pearson_pdf https://plus.pearson.com/eplayer/pdfassets/prod1/109693/4e309576-c7ad-42f5-9663-ce760d9e20bc

results in
Traceback (most recent call last):
  File "/home/withingssync/.local/bin/pearson_pdf", line 8, in <module>
    sys.exit(main())
  File "/home/withingssync/.local/lib/python3.6/site-packages/pearson_pdf/__main__.py", line 26, in main
    combine_pages(download_pages(args.book), args.save_path)
  File "/home/withingssync/.local/lib/python3.6/site-packages/pearson_pdf/__init__.py", line 49, in combine_pages
    page_0 = pages[0]
IndexError: list index out of range

Happy to accept this is user error but not having much luck decoding what I'm doing wrong... TIA!

**Comment by jyooru** [comment]
Hmm, you seem to be receiving a different foxitAssetURL compared to what I receive.
I receive `https://d2f01w1orx96i0.cloudfront.net/resources/products/epubs/generated/*id*/foxit-assets`.

How are you accessing the page to get your foxitAssetURL?
My page is `https://reader-sin-prod.gls.pearson-intl.com/product/*id*`, and I access it through `https://www.pearsonplaces.com.au/dash`.

**Comment by jyooru** [comment]
> not having much luck decoding what I'm doing wrong
I agree, I'll add a proper error message now

**Comment by rlsolomon** [comment]
> Hmm, you seem to be receiving a different foxitAssetURL compared to what I receive.
> I receive `https://d2f01w1orx96i0.cloudfront.net/resources/products/epubs/generated/*id*/foxit-assets`.
> 
> How are you accessing the page to get your foxitAssetURL?
> My page is `https://reader-sin-prod.gls.pearson-intl.com/product/*id*`, and I access it through `https://www.pearsonplaces.com.au/dash`.

portal.mypearson.com which takes one to https://openvellum.ecollege.com/ which links to https://vizedhtmlcontent.next.ecollege.com/(NEXT(4245680ef8))/Main/CourseMode/VizedHtmlView/View.ed?eclg_courseId=16958242&refid=136&# which ultimately opens https://plus.pearson.com/courses/6014273/products/109693/pages/i?locale=&platformId=1030

**Comment by jyooru** [comment]
It looks like you're accessing your book from a completely different reader than from where I access my books. Not sure why Pearson runs two different versions.

I would still like to support this version if you are interested. I can't access that book using my account, so could you follow these steps so I can support this?
1. Open up developer tools.
2. Go to the network tab.
3. In the reader, go to a different page.
4. In the developer tools, you should see the page be fetched from a server. Double clicking it should open/download the page.
5. Right click and select copy URL and paste it here.

Could you do this for page 1 and 2? Then I'll be able to take a look at what I need to do to get this working with my code.

Of course, if you have experience with Python you can have a go at implementing this yourself with my code. Feel free to let me know if you have any questions.

**Comment by rlsolomon** [comment]
Hmmm, I see something like 132 requests in the network tab of various types: document, sylesheet, scripts, xhr, shr, preflight, etc...  

There are only 3 document links, two appear related to login/authentication:
1) https://login.pearson.com/v1/piapi/login/oidcauthorize?client_id=<someidentifier>&redirect_uri=https%3A%2F%2Fplus.pearson.com%2Fcourses%2F6014273%2Fproducts%2F109693%2Fpages%2Fi%3Flocale%3D%26platformId%3D1030&nonce=123454321&prompt=none
2) https://plus.pearson.com/courses/6014273/products/109693/pages/i?locale=&platformId=1030&iesCode=R22Zs6MndS
3) https://login.pearson.com/v1/piapi/login/html/v2/checkSessionFrame.html?v=3.49.2

Double-clicking those brings up a new tab - but always on the first page of the PDF no matter where I am when I capture the info.  It certainly feels like FoxIt is running against a complete PDF document vs multiple PDF files but I can't prove that.

**Comment by jyooru** [comment]
Hmm, all three of those links are blocked behind authentication for me. 
My book's pages are image files which are not blocked behind authentication (for some reason).

It's also possible that my book is the one that is different. I only have one pearson book.

Either way, considering I can't access those links it's going to be hard for me to implement this.

**Comment by rlsolomon** [comment]
Thanks, yeah I'm fearing this one is quite different, but I'd appreciate any info you can provide on suggested approaches. I can create a discord account I guess and hit you up that way rather than bog down the issues here.

**Comment by jyooru** [comment]
Alright, the first thing I would do is figure out where it is downloading the pdf/pages from.

If you want to talk somewhere else I have a few accounts: https://joel.tokyo/contact
I’m also happy to sign up to a service if that suits you better.

**Comment by jyooru** [comment]
Hi @rlsolomon, can you see if going to `{your foxitAssetURL}/foxit-assets/pages/page1` downloads the first page of your book?

**Comment by rlsolomon** [comment]
I get Access Denied for that URL but some fiddling around shows the "which ultimately opens" URL above does go to specific pages in the viewer: e.g. [https://plus.pearson.com/courses/6014273/products/109693/pages/78](url) brings up page 78...

**Comment by jyooru** [comment]
Hi! Thanks for opening this issue, but I've decided that I'm not going to fix this issue as I cannot debug it from my computer. As it needs your credentials, it's incredibly hard to fix downloading your book. All of the books I have work with this tool and I'm not sure why your book is different. There might be an alternative you can use.
