### ISSUE TITLE
pearson_pdf.PageDownloadError - etext-ise.pearson.com

### ISSUE THREAD

**Issue by beninifez** [jyooru/pearson-pdf#48]
As in the title, when I run the script this error comes out. I''ve read in another issue that Pearson has multiple readers(don't know why), and for me it is another one: the link that I get in the developer mode is https://etext-ise.pearson.com/eplayer/pdfassets/prod1/77493/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx.
What can I do?

**Comment by jyooru** [comment]
Yep, looks like this is another one. Now I'm wondering how many there are...

Could you have a look at the info in this comment? https://github.com/jyooru/pearson-pdf/issues/38#issuecomment-913081711

If the info in that comment doesn't work, you could also try going to `{your foxitAssetURL}/foxit-assets/pages/page1`.

**Comment by jyooru** [comment]
Linking to #38

**Comment by beninifez** [comment]
The link which downloads the page in png is this: https://etext-ise.pearson.com/eplayer/pdfassets/prod1/77493/665f30b4-2b32-4f09-a09c-5909187eded3/pages/page1
For all the pages it's the same, it only changes the final page number

**Comment by jyooru** [comment]
Awesome! It's the same way to get the pages as my book, just a different domain. Your book is also behind authentication, so I'll need to get that working. I'll start working on this soon.

**Comment by beninifez** [comment]
Thanks!!

**Comment by jyooru** [comment]
Hi! Thanks for opening this issue, but I've decided that I'm not going to fix this issue as I cannot debug it from my computer. As it needs your credentials, it's incredibly hard to fix downloading your book. All of the books I have work with this tool and I'm not sure why your book is different. There might be an alternative you can use.
