### ISSUE TITLE
Could not find a version that satisfies the requirement pearson-pdf

### ISSUE THREAD

**Issue by easymax** [jyooru/pearson-pdf#77]
Once I try to install I get the following error: 

ERROR: Could not find a version that satisfies the requirement pearson-pdf (from versions: none)
ERROR: No matching distribution found for pearson-pdf

**Comment by jyooru** [comment]
Can you please post your python version, how you're installing pearson-pdf and what OS you are using?

**Comment by jyooru** [comment]
I'm going to close this issue as I haven't had a response for a while now. Please create another one if needed.
